[2020-03-23 14:40:46,041] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 14:40:46,108] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 14:40:47,446] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 14:40:47,448] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 14:40:47,680] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 14:40:47,693] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 14:40:54,299] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 14:40:54] "POST /v1/statistisc_analyse/qi_situation HTTP/1.1" 200 -]
[2020-03-23 14:42:23,931] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 14:42:24,007] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 14:42:25,446] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 14:42:25,448] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 14:42:25,474] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 14:42:25,486] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 14:45:09,075] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 14:45:09] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 15:00:03,701] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 15:00:03,705] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 15:00:05,120] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 15:00:05,123] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 15:00:05,150] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 15:00:05,161] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 15:00:05,696] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 15:00:05] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 15:00:48,533] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 15:00:48,606] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 15:00:49,993] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 15:00:49,996] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 15:00:50,023] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 15:00:50,034] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 15:02:06,011] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 15:02:06] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 15:03:20,368] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 15:03:20,440] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 15:03:21,792] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 15:03:21,795] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 15:03:21,821] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 15:03:21,832] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 15:03:24,867] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 15:03:24] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 15:10:01,109] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 15:10:01,182] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 15:10:02,697] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 15:10:02,699] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 15:10:02,725] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 15:10:02,735] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 15:10:07,904] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 15:10:07] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 15:11:26,793] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 15:11:26,857] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 15:11:28,211] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 15:11:28,213] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 15:11:28,239] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 15:11:28,250] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 15:19:08,913] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 15:19:08,981] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 15:19:10,352] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 15:19:10,354] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 15:19:10,380] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 15:19:10,391] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 15:19:13,131] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 15:19:13] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 15:30:22,203] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 15:30:22,273] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 15:30:23,653] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 15:30:23,655] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 15:30:23,681] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 15:30:23,691] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 15:39:49,533] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 15:39:49,616] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 15:39:51,052] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 15:39:51,054] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 15:39:51,081] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 15:39:51,092] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 15:39:53,133] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 15:39:53] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 15:40:23,982] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 15:40:24,074] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 15:40:25,444] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 15:40:25,447] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 15:40:25,472] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 15:40:25,483] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 15:40:26,210] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 15:40:26] "POST /v1/qiacall/test11 HTTP/1.1" 500 -]
[2020-03-23 15:40:37,320] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 15:40:37,390] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 15:40:38,813] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 15:40:38,815] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 15:40:38,844] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 15:40:38,854] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 15:40:39,140] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 15:40:39] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 15:43:38,494] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 15:43:38,570] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 15:43:40,032] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 15:43:40,034] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 15:43:40,059] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 15:43:40,070] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 15:45:26,105] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 15:45:26,190] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 15:45:27,701] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 15:45:27,703] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 15:45:27,730] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 15:45:27,740] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 15:45:27,916] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 15:45:27] "POST /v1/qiacall/test11 HTTP/1.1" 500 -]
[2020-03-23 15:45:39,595] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 15:45:39,662] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 15:45:41,057] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 15:45:41,059] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 15:45:41,085] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 15:45:41,096] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 15:45:42,745] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 15:45:42] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 15:51:08,691] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 15:51:08,760] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 15:51:10,178] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 15:51:10,180] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 15:51:10,206] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 15:51:10,217] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 15:51:28,941] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 15:51:29,002] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 15:51:30,400] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 15:51:30,402] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 15:51:30,427] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 15:51:30,439] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 15:51:30,776] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 15:51:30] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 15:52:40,520] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 15:52:40,597] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 15:52:42,046] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 15:52:42,048] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 15:52:42,074] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 15:52:42,086] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 15:52:46,902] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 15:52:46] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 15:53:14,933] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 15:53:15,009] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 15:53:16,375] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 15:53:16,377] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 15:53:16,403] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 15:53:16,414] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 15:53:23,557] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 15:53:23,650] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 15:53:25,063] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 15:53:25,065] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 15:53:25,090] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 15:53:25,101] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 15:53:27,304] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 15:53:27] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 15:56:12,969] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 15:56:13,039] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 15:56:14,489] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 15:56:14,492] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 15:56:14,520] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 15:56:14,534] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 15:56:15,012] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 15:56:15] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 15:56:36,873] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 15:56:36,938] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 15:56:38,340] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 15:56:38,343] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 15:56:38,374] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 15:56:38,387] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 15:56:43,880] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 15:56:43] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 15:57:15,812] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 15:57:15] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 15:57:15,821] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 15:57:15,910] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 15:57:17,328] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 15:57:17,331] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 15:57:17,358] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 15:57:17,369] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 15:57:19,384] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 15:57:19] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 15:58:04,180] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 15:58:04,263] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 15:58:05,655] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 15:58:05,658] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 15:58:05,684] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 15:58:05,695] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 15:58:06,090] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 15:58:06] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 15:58:57,147] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 15:58:57,212] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 15:58:58,743] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 15:58:58,746] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 15:58:58,774] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 15:58:58,785] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 16:00:30,913] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 16:00:30,976] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 16:00:32,408] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 16:00:32,410] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 16:00:32,436] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 16:00:32,448] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 16:00:33,030] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 16:00:33] "POST /v1/qiacall/test11 HTTP/1.1" 500 -]
[2020-03-23 16:01:05,298] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 16:01:05,392] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 16:01:06,795] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 16:01:06,797] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 16:01:06,823] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 16:01:06,834] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 16:01:07,298] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 16:01:07] "POST /v1/qiacall/test11 HTTP/1.1" 500 -]
[2020-03-23 16:01:59,456] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 16:01:59,535] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 16:02:00,974] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 16:02:00,976] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 16:02:01,001] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 16:02:01,012] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 16:02:01,273] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 16:02:01] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 16:04:19,936] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 16:04:20,027] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 16:04:21,437] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 16:04:21,440] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 16:04:21,464] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 16:04:21,476] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 16:04:21,676] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 16:04:21] "POST /v1/qiacall/test11 HTTP/1.1" 500 -]
[2020-03-23 16:04:36,818] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 16:04:36,898] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 16:04:38,309] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 16:04:38,311] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 16:04:38,335] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 16:04:38,346] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 16:04:38,896] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 16:04:38] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 16:05:20,407] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 16:05:20,475] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 16:05:21,893] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 16:05:21,896] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 16:05:21,937] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 16:05:21,947] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 16:05:22,278] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 16:05:22] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 16:12:47,023] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 16:12:47,127] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 16:12:48,550] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 16:12:48,553] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 16:12:48,578] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 16:12:48,589] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 16:12:48,753] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 16:12:48] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 16:15:26,038] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 16:15:26,184] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 16:15:27,609] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 16:15:27,611] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 16:15:27,638] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 16:15:27,651] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 16:15:28,589] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 16:15:28] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 16:16:36,664] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 16:16:36,733] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 16:16:38,175] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 16:16:38,178] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 16:16:38,203] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 16:16:38,214] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 16:16:38,498] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 16:16:38] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 16:17:19,194] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 16:17:19,261] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 16:17:20,652] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 16:17:20,654] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 16:17:20,679] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 16:17:20,689] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 16:20:25,552] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 16:20:25,621] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 16:20:27,025] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 16:20:27,028] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 16:20:27,054] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 16:20:27,067] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 16:20:27,541] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 16:20:27] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 16:27:04,772] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 16:27:04,777] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 16:27:06,154] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 16:27:06,157] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 16:27:06,182] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 16:27:06,193] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 16:27:06,711] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 16:27:06] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 16:27:07,672] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 16:27:07] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 16:29:15,757] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 16:29:15,825] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 16:29:17,187] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 16:29:17,190] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 16:29:17,215] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 16:29:17,225] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 16:33:12,633] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 16:33:12,708] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 16:33:14,134] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 16:33:14,137] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 16:33:14,161] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 16:33:14,172] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 16:33:14,770] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 16:33:14] "POST /v1/qiacall/test11 HTTP/1.1" 500 -]
[2020-03-23 16:33:43,486] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 16:33:43,556] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 16:33:44,912] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 16:33:44,915] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 16:33:44,940] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 16:33:44,951] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 16:33:47,045] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 16:33:47] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 16:34:47,990] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 16:34:48,078] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 16:34:49,490] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 16:34:49,492] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 16:34:49,519] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 16:34:49,530] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 16:34:49,636] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 16:34:49] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 16:34:56,020] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 16:34:56] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 16:34:57,761] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 16:34:57] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 16:35:26,442] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 16:35:26] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 16:36:18,367] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 16:36:18,447] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 16:36:19,834] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 16:36:19,837] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 16:36:19,861] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 16:36:19,872] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 16:36:20,004] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 16:36:20] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 16:39:35,754] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 16:39:35,823] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 16:39:37,245] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 16:39:37,247] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 16:39:37,272] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 16:39:37,284] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 16:39:37,785] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 16:39:37] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 16:43:10,406] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 16:43:10,468] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 16:43:11,832] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 16:43:11,834] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 16:43:11,860] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 16:43:11,870] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 16:43:37,637] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 16:43:37,697] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 16:43:39,069] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 16:43:39,071] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 16:43:39,097] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 16:43:39,108] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 16:44:54,859] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 16:44:54,919] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 16:44:56,275] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 16:44:56,277] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 16:44:56,302] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 16:44:56,314] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 16:45:06,982] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 16:45:07,055] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 16:45:08,440] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 16:45:08,442] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 16:45:08,467] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 16:45:08,477] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 16:45:09,733] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 16:45:09] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 16:45:16,848] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 16:45:16,916] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 16:45:18,322] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 16:45:18,325] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 16:45:18,351] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 16:45:18,361] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 16:45:18,778] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 16:45:18] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 16:45:49,954] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 16:45:50,021] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 16:45:51,373] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 16:45:51,375] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 16:45:51,400] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 16:45:51,411] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 16:45:52,303] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 16:45:52] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 16:47:00,278] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 16:47:00,348] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 16:47:01,783] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 16:47:01,785] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 16:47:01,811] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 16:47:01,822] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 16:47:02,311] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 16:47:02] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 16:47:43,913] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 16:47:43,974] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 16:47:45,346] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 16:47:45,349] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 16:47:45,374] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 16:47:45,385] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 16:47:45,651] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 16:47:45] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 16:48:20,500] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 16:48:20,573] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 16:48:21,947] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 16:48:21,950] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 16:48:21,985] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 16:48:21,996] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 16:48:22,541] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 16:48:22] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 16:54:42,576] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 16:54:42,648] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 16:54:44,048] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 16:54:44,050] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 16:54:44,076] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 16:54:44,087] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 16:54:45,318] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 16:54:45] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 16:55:56,453] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 16:55:56,521] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 16:55:57,922] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 16:55:57,924] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 16:55:57,951] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 16:55:57,961] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 16:55:58,528] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 16:55:58] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 16:56:28,390] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 16:56:28,483] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 16:56:29,868] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 16:56:29,870] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 16:56:29,895] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 16:56:29,905] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 16:56:30,502] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 16:56:30] "POST /v1/qiacall/test11 HTTP/1.1" 200 -]
[2020-03-23 16:58:39,210] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 16:58:39,274] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 16:58:40,614] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 16:58:40,616] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 16:58:40,641] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 16:58:40,652] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 16:58:41,839] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 16:58:41] "POST /v1/token HTTP/1.1" 200 -]
[2020-03-23 17:00:13,282] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 17:00:13,362] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 17:00:14,883] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 17:00:14,885] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 17:00:14,914] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 17:00:14,927] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 17:00:15,348] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 17:00:15] "POST /v1/qiacall/list HTTP/1.1" 200 -]
[2020-03-23 17:01:32,314] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 17:01:32,406] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 17:01:33,966] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 17:01:33,969] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 17:01:33,996] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 17:01:34,009] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 17:04:49,028] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 17:04:49,089] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 17:04:50,474] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 17:04:50,476] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 17:04:50,502] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 17:04:50,513] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 17:04:50,983] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 17:04:50] "POST /v1/qiacall/list HTTP/1.1" 200 -]
[2020-03-23 17:04:59,967] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 17:05:00,063] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 17:05:01,431] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 17:05:01,433] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 17:05:01,458] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 17:05:01,469] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 17:05:01,700] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 17:05:01] "POST /v1/qiacall/list HTTP/1.1" 200 -]
[2020-03-23 17:09:34,393] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiacall.py', reloading]
[2020-03-23 17:09:34,465] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 17:09:35,914] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 17:09:35,916] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 17:09:35,941] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 182-410-545]
[2020-03-23 17:09:35,952] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-23 17:09:36,250] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 17:09:36] "POST /v1/qiacall/list HTTP/1.1" 200 -]
[2020-03-23 17:32:58,249] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\speech_qia.py', reloading]
[2020-03-23 17:32:58,320] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 17:35:31,670] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 17:38:32,205] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 17:38:32,216] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:7779/ (Press CTRL+C to quit)]
[2020-03-23 17:45:41,942] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 17:45:41] "POST /v1/qiacase/list HTTP/1.1" 200 -]
[2020-03-23 17:47:52,240] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 17:47:52] "GET / HTTP/1.1" 404 -]
[2020-03-23 17:47:53,695] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 17:47:53] "GET /favicon.ico HTTP/1.1" 404 -]
[2020-03-23 17:48:02,672] [ERROR] [app.py -- log_exception:1891] [Exception on /v1/token [POST]]
Traceback (most recent call last):
  File "D:\a_yunjia_project\shnaghai_project\shanghai_env\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\a_yunjia_project\shnaghai_project\shanghai_env\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\a_a_a_project\AI_Speech_QIA\src\app\api\sysmng\token.py", line 20, in token_get
    form = LoginForm().validate_for_api()
  File "D:\a_a_a_project\AI_Speech_QIA\src\app\validators\base.py", line 27, in validate_for_api
    raise ParameterException(msg=self.errors.values())
app.libs.error_code.ParameterException: 400 Bad Request: dict_values([['账号：不允许为空']])

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a_yunjia_project\shnaghai_project\shanghai_env\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\a_yunjia_project\shnaghai_project\shanghai_env\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\a_yunjia_project\shnaghai_project\shanghai_env\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\a_yunjia_project\shnaghai_project\shanghai_env\lib\site-packages\flask\app.py", line 2116, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "D:\a_yunjia_project\shnaghai_project\shanghai_env\lib\site-packages\werkzeug\wrappers\base_response.py", line 269, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "D:\a_yunjia_project\shnaghai_project\shanghai_env\lib\site-packages\werkzeug\test.py", line 1119, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "D:\a_yunjia_project\shnaghai_project\shanghai_env\lib\site-packages\werkzeug\exceptions.py", line 191, in __call__
    response = self.get_response(environ)
  File "D:\a_yunjia_project\shnaghai_project\shanghai_env\lib\site-packages\werkzeug\exceptions.py", line 182, in get_response
    return Response(self.get_body(environ), self.code, headers)
  File "D:\a_a_a_project\AI_Speech_QIA\src\app\libs\error.py", line 32, in get_body
    text = json.dumps(body)
  File "D:\a_yunjia_project\shnaghai_project\shanghai_env\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "D:\job_soft\python37\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "D:\job_soft\python37\Lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\job_soft\python37\Lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\a_a_a_project\AI_Speech_QIA\src\app\app.py", line 19, in default
    raise ServerError()
app.libs.error_code.ServerError: 500 Internal Server Error: None
[2020-03-23 17:48:02,970] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 17:48:02] "POST /v1/token HTTP/1.1" 500 -]
[2020-03-23 17:48:58,985] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 17:48:58] "POST /v1/token HTTP/1.1" 200 -]
[2020-03-23 17:49:24,470] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 17:49:24] "GET /v1/qiacase/del HTTP/1.1" 404 -]
[2020-03-23 17:49:45,737] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 17:49:45,750] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 17:49:47,242] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 17:49:47,244] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 17:49:47,287] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 764-970-292]
[2020-03-23 17:49:47,298] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:7779/ (Press CTRL+C to quit)]
[2020-03-23 17:49:48,057] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 17:49:48] "GET /v1/qiacase/del HTTP/1.1" 404 -]
[2020-03-23 17:49:49,495] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 17:49:49] "GET /v1/qiacase/del HTTP/1.1" 404 -]
[2020-03-23 17:50:05,093] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 17:50:05] "GET /v1/qiacase/del/3 HTTP/1.1" 403 -]
[2020-03-23 17:52:42,374] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 17:52:42] "POST /v1/qiacase/list HTTP/1.1" 200 -]
[2020-03-23 17:55:19,675] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 17:55:19] "POST /v1/user HTTP/1.1" 401 -]
[2020-03-23 17:56:12,205] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 17:56:12] "POST /v1/user HTTP/1.1" 500 -]
[2020-03-23 17:56:52,732] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 17:56:52] "POST /v1/user HTTP/1.1" 500 -]
[2020-03-23 17:57:44,376] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\models\\qi_qia_models.py', reloading]
[2020-03-23 17:57:44,472] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 17:57:45,985] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 17:57:45,988] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 17:57:46,015] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 764-970-292]
[2020-03-23 17:57:46,025] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:7779/ (Press CTRL+C to quit)]
[2020-03-23 17:59:05,482] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 17:59:05] "POST /v1/user HTTP/1.1" 500 -]
[2020-03-23 17:59:25,607] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 17:59:25,611] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 17:59:27,078] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 17:59:27,080] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 17:59:27,106] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 764-970-292]
[2020-03-23 17:59:27,117] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:7779/ (Press CTRL+C to quit)]
[2020-03-23 17:59:52,209] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\sysmng\\user.py', reloading]
[2020-03-23 17:59:52,292] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 17:59:53,825] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 17:59:53,828] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 17:59:53,853] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 764-970-292]
[2020-03-23 17:59:53,864] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:7779/ (Press CTRL+C to quit)]
[2020-03-23 17:59:54,177] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 17:59:54] "POST /v1/user HTTP/1.1" 500 -]
[2020-03-23 18:00:00,269] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 18:00:00,273] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 18:00:01,770] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 18:00:01,772] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 18:00:01,800] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 764-970-292]
[2020-03-23 18:00:01,812] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:7779/ (Press CTRL+C to quit)]
[2020-03-23 18:00:03,573] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 18:00:03] "POST /v1/user HTTP/1.1" 500 -]
[2020-03-23 18:00:18,668] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\validators\\forms_v1.py', reloading]
[2020-03-23 18:00:18,753] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 18:00:20,261] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 18:00:20,263] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 18:00:20,289] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 764-970-292]
[2020-03-23 18:00:20,299] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:7779/ (Press CTRL+C to quit)]
[2020-03-23 18:00:22,198] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 18:00:22] "POST /v1/user HTTP/1.1" 500 -]
[2020-03-23 18:00:57,367] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\validators\\forms_v1.py', reloading]
[2020-03-23 18:00:57,460] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 18:00:58,994] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 18:00:58,997] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 18:00:59,024] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 764-970-292]
[2020-03-23 18:00:59,034] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:7779/ (Press CTRL+C to quit)]
[2020-03-23 18:01:03,293] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [23/Mar/2020 18:01:03] "POST /v1/user HTTP/1.1" 500 -]
[2020-03-23 18:23:31,867] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\statistisc_analyse.py', reloading]
[2020-03-23 18:23:31,952] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 18:23:33,464] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 18:23:33,466] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 18:23:33,492] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 764-970-292]
[2020-03-23 18:23:33,503] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:7779/ (Press CTRL+C to quit)]
[2020-03-23 18:31:14,531] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\statistisc_analyse.py', reloading]
[2020-03-23 18:31:14,632] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-23 18:31:16,138] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-23 18:31:16,140] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-23 18:31:16,165] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 764-970-292]
[2020-03-23 18:31:16,176] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:7779/ (Press CTRL+C to quit)]
[2020-03-24 14:20:23,751] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 14:20:23,766] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 14:20:25,242] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 14:20:25,244] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 14:20:25,270] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 764-970-292]
[2020-03-24 14:20:25,281] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:7779/ (Press CTRL+C to quit)]
[2020-03-24 14:37:37,499] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\statistisc_analyse.py', reloading]
[2020-03-24 14:37:37,651] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 14:37:39,662] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 14:37:39,664] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 14:37:39,696] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 764-970-292]
[2020-03-24 14:37:39,708] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:7779/ (Press CTRL+C to quit)]
[2020-03-24 14:37:57,071] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [24/Mar/2020 14:37:57] "POST /v1/statistisc_analyse/op_dura_business_list HTTP/1.1" 500 -]
[2020-03-24 14:44:40,775] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\validators\\forms_v1.py', reloading]
[2020-03-24 14:44:40,886] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 14:44:42,578] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 14:44:42,580] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 14:44:42,607] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 764-970-292]
[2020-03-24 14:44:42,618] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:7779/ (Press CTRL+C to quit)]
[2020-03-24 14:49:36,905] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [24/Mar/2020 14:49:36] "POST /v1/statistisc_analyse/op_dura_business_list HTTP/1.1" 200 -]
[2020-03-24 14:54:07,751] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\sysmng\\user.py', reloading]
[2020-03-24 14:54:07,948] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 14:54:09,499] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 14:54:09,501] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 14:54:09,528] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 764-970-292]
[2020-03-24 14:54:09,538] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:7779/ (Press CTRL+C to quit)]
[2020-03-24 14:54:56,348] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\models\\qi_qia_models.py', reloading]
[2020-03-24 14:54:56,496] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 14:54:58,086] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 14:54:58,088] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 14:54:58,116] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 764-970-292]
[2020-03-24 14:54:58,126] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:7779/ (Press CTRL+C to quit)]
[2020-03-24 14:57:47,993] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\validators\\forms_v1.py', reloading]
[2020-03-24 14:57:48,079] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 14:57:49,713] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 14:57:49,715] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 14:57:49,741] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 764-970-292]
[2020-03-24 14:57:49,751] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:7779/ (Press CTRL+C to quit)]
[2020-03-24 15:22:14,010] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\configure.py', reloading]
[2020-03-24 15:22:14,108] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 15:22:16,386] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 15:45:51,363] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 15:45:51,467] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 15:45:52,955] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 15:45:52,957] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 15:45:53,088] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 764-970-292]
[2020-03-24 15:45:53,098] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-24 15:52:19,650] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\statistisc_analyse.py', reloading]
[2020-03-24 15:52:19,787] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 15:52:21,881] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 15:52:21,883] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 15:52:21,913] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 764-970-292]
[2020-03-24 15:52:21,926] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-24 15:55:37,352] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\statistisc_analyse.py', reloading]
[2020-03-24 15:55:37,528] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 15:55:39,492] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 15:55:39,494] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 15:55:39,524] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 764-970-292]
[2020-03-24 15:55:39,535] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-24 15:56:03,232] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 15:56:03,236] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 15:56:04,772] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 15:56:04,774] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 15:56:04,800] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 764-970-292]
[2020-03-24 15:56:04,811] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-24 15:56:10,578] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 15:56:10,582] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 15:56:12,139] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 15:56:12,141] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 15:56:12,168] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 764-970-292]
[2020-03-24 15:56:12,179] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-24 15:56:25,560] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\statistisc_analyse.py', reloading]
[2020-03-24 15:56:25,685] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 15:56:26,686] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\statistisc_analyse.py', reloading]
[2020-03-24 15:56:26,860] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 15:56:27,736] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 15:56:27,739] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 15:56:27,773] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 764-970-292]
[2020-03-24 15:56:27,786] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-24 15:56:28,673] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 15:56:28,676] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 15:56:28,702] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 764-970-292]
[2020-03-24 15:56:28,713] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-24 15:56:33,502] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 15:56:33,506] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 15:56:35,146] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 15:56:35,148] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 15:56:35,174] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 764-970-292]
[2020-03-24 15:56:35,186] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-24 15:59:30,151] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 15:59:30,330] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 15:59:32,769] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 15:59:32,771] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 15:59:32,840] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 764-970-292]
[2020-03-24 15:59:32,850] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-24 16:00:34,225] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [24/Mar/2020 16:00:34] "POST /v1/statistisc_analyse/op_dura_business_list HTTP/1.1" 200 -]
[2020-03-24 16:00:54,343] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\statistisc_analyse.py', reloading]
[2020-03-24 16:00:54,508] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 16:00:57,368] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 16:00:57,373] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 16:00:57,411] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 764-970-292]
[2020-03-24 16:00:57,435] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-24 16:01:19,468] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [24/Mar/2020 16:01:19] "POST /v1/statistisc_analyse/op_hot_words HTTP/1.1" 500 -]
[2020-03-24 16:01:35,177] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [24/Mar/2020 16:01:35] "POST /v1/statistisc_analyse/op_hot_words HTTP/1.1" 200 -]
[2020-03-24 16:02:09,466] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [24/Mar/2020 16:02:09] "POST /v1/statistisc_analyse/op_business HTTP/1.1" 200 -]
[2020-03-24 16:02:39,673] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [24/Mar/2020 16:02:39] "POST /v1/statistisc_analyse/op_repeat HTTP/1.1" 200 -]
[2020-03-24 16:05:52,633] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\statistisc_analyse.py', reloading]
[2020-03-24 16:05:52,711] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 16:05:54,218] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 16:05:54,221] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 16:05:54,246] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 764-970-292]
[2020-03-24 16:05:54,257] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-24 16:06:07,818] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [24/Mar/2020 16:06:07] "POST /v1/statistisc_analyse/op_repeat HTTP/1.1" 500 -]
[2020-03-24 16:06:53,022] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\statistisc_analyse.py', reloading]
[2020-03-24 16:06:53,162] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 16:06:54,858] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 16:06:54,861] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 16:06:54,889] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 764-970-292]
[2020-03-24 16:06:54,902] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-24 16:06:55,287] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [24/Mar/2020 16:06:55] "POST /v1/statistisc_analyse/op_repeat HTTP/1.1" 200 -]
[2020-03-24 16:27:12,778] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 16:27:12,782] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 16:27:14,259] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 16:27:14,261] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 16:27:14,286] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 764-970-292]
[2020-03-24 16:27:14,297] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-24 16:41:15,915] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\configure.py', reloading]
[2020-03-24 16:41:16,039] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 17:23:48,541] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 17:23:48,546] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 17:23:49,933] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 17:23:49,935] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 17:23:49,960] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 764-970-292]
[2020-03-24 17:23:49,971] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-24 17:24:48,597] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\statistisc_analyse.py', reloading]
[2020-03-24 17:24:48,753] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 17:43:57,472] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 17:43:57,476] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 17:43:58,788] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 17:43:58,790] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 17:43:58,814] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 764-970-292]
[2020-03-24 17:43:58,825] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-24 17:51:49,260] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\api\\v1\\qiaproj.py', reloading]
[2020-03-24 17:51:49,327] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 17:51:50,673] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 17:51:50,675] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 17:51:50,699] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 764-970-292]
[2020-03-24 17:51:50,710] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-24 17:59:24,140] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [24/Mar/2020 17:59:24] "POST /v1/qiacall/list HTTP/1.1" 200 -]
[2020-03-24 18:02:15,608] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [24/Mar/2020 18:02:15] "POST /v1/user HTTP/1.1" 500 -]
[2020-03-24 18:03:28,891] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [24/Mar/2020 18:03:28] "POST /v1/user HTTP/1.1" 500 -]
[2020-03-24 18:05:22,111] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 18:05:22,116] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 18:05:23,525] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 18:05:23,528] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 18:05:23,553] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 764-970-292]
[2020-03-24 18:05:23,565] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-24 18:05:24,426] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [24/Mar/2020 18:05:24] "POST /v1/user HTTP/1.1" 500 -]
[2020-03-24 18:05:43,476] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [24/Mar/2020 18:05:43] "POST /v1/user HTTP/1.1" 500 -]
[2020-03-24 18:05:43,493] [INFO] [_internal.py -- _log:122] [ * Detected change in 'D:\\a_a_a_project\\AI_Speech_QIA\\src\\app\\validators\\forms_v1.py', reloading]
[2020-03-24 18:05:43,602] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 18:05:45,123] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 18:05:45,125] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 18:05:45,152] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 764-970-292]
[2020-03-24 18:05:45,166] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-24 18:05:55,935] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [24/Mar/2020 18:05:55] "POST /v1/user HTTP/1.1" 500 -]
[2020-03-24 18:09:41,311] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [24/Mar/2020 18:09:41] "GET /v1/qiacase/del/4 HTTP/1.1" 403 -]
[2020-03-24 19:42:16,459] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 19:42:16,528] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 19:42:17,892] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 19:42:17,894] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 19:42:18,026] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 764-970-292]
[2020-03-24 19:42:18,039] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-24 19:55:50,294] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 19:55:50,299] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 19:55:51,536] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 19:55:51,539] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 19:55:51,564] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 130-757-431]
[2020-03-24 19:55:51,574] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-24 20:03:46,483] [INFO] [_internal.py -- _log:122] [ * Detected change in 'F:\\yjcloud-learn\\python_learn\\frame_api\\src\\app\\api\\v1\\learn.py', reloading]
[2020-03-24 20:03:46,552] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 20:03:47,859] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 20:03:47,862] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 20:03:47,886] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 130-757-431]
[2020-03-24 20:03:47,897] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-24 20:04:27,495] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [24/Mar/2020 20:04:27] "POST /v1/learn/op_reason_trend HTTP/1.1" 200 -]
[2020-03-24 20:18:15,954] [INFO] [_internal.py -- _log:122] [ * Detected change in 'F:\\yjcloud-learn\\python_learn\\frame_api\\src\\app\\api\\v1\\learn.py', reloading]
[2020-03-24 20:18:16,102] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 20:18:17,453] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 20:18:17,456] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 20:18:17,481] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 130-757-431]
[2020-03-24 20:18:17,492] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-24 20:19:19,947] [INFO] [_internal.py -- _log:122] [ * Detected change in 'F:\\yjcloud-learn\\python_learn\\frame_api\\src\\app\\api\\v1\\learn.py', reloading]
[2020-03-24 20:19:20,010] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 20:19:21,388] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 20:19:21,392] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 20:19:21,418] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 130-757-431]
[2020-03-24 20:19:21,431] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-24 20:19:56,216] [INFO] [_internal.py -- _log:122] [ * Detected change in 'F:\\yjcloud-learn\\python_learn\\frame_api\\src\\app\\api\\v1\\learn.py', reloading]
[2020-03-24 20:19:56,283] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 20:19:57,646] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 20:19:57,649] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 20:19:57,676] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 130-757-431]
[2020-03-24 20:19:57,686] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-24 20:20:16,280] [INFO] [_internal.py -- _log:122] [ * Detected change in 'F:\\yjcloud-learn\\python_learn\\frame_api\\src\\app\\api\\v1\\learn.py', reloading]
[2020-03-24 20:20:16,344] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 20:20:17,714] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 20:20:17,717] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 20:20:17,742] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 130-757-431]
[2020-03-24 20:20:17,753] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-24 20:20:55,973] [INFO] [_internal.py -- _log:122] [ * Detected change in 'F:\\yjcloud-learn\\python_learn\\frame_api\\src\\app\\api\\v1\\learn.py', reloading]
[2020-03-24 20:20:56,113] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 20:20:57,485] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 20:20:57,488] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 20:20:57,513] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 130-757-431]
[2020-03-24 20:20:57,523] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-24 20:23:23,062] [INFO] [_internal.py -- _log:122] [ * Detected change in 'F:\\yjcloud-learn\\python_learn\\frame_api\\src\\app\\api\\v1\\learn.py', reloading]
[2020-03-24 20:23:23,121] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 20:23:24,378] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 20:23:24,381] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 20:23:24,405] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 130-757-431]
[2020-03-24 20:23:24,416] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-24 20:23:25,507] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [24/Mar/2020 20:23:25] "POST /v1/learn/op_reason_trend HTTP/1.1" 500 -]
[2020-03-24 20:23:51,133] [INFO] [_internal.py -- _log:122] [ * Detected change in 'F:\\yjcloud-learn\\python_learn\\frame_api\\src\\app\\api\\v1\\learn.py', reloading]
[2020-03-24 20:23:51,195] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 20:23:52,480] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 20:23:52,482] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 20:23:52,507] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 130-757-431]
[2020-03-24 20:23:52,517] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-24 20:23:57,738] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [24/Mar/2020 20:23:57] "POST /v1/learn/op_reason_trend HTTP/1.1" 500 -]
[2020-03-24 20:24:16,951] [INFO] [_internal.py -- _log:122] [ * Detected change in 'F:\\yjcloud-learn\\python_learn\\frame_api\\src\\app\\api\\v1\\learn.py', reloading]
[2020-03-24 20:24:17,018] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 20:24:18,354] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 20:24:18,357] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 20:24:18,382] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 130-757-431]
[2020-03-24 20:24:18,392] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-24 20:24:18,894] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [24/Mar/2020 20:24:18] "POST /v1/learn/op_reason_trend HTTP/1.1" 200 -]
[2020-03-24 20:24:54,479] [INFO] [_internal.py -- _log:122] [ * Detected change in 'F:\\yjcloud-learn\\python_learn\\frame_api\\src\\app\\api\\v1\\learn.py', reloading]
[2020-03-24 20:24:54,587] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 20:24:55,929] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 20:24:55,932] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 20:24:55,956] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 130-757-431]
[2020-03-24 20:24:55,966] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-24 20:24:56,301] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [24/Mar/2020 20:24:56] "POST /v1/learn/op_reason_trend HTTP/1.1" 200 -]
[2020-03-24 20:30:47,350] [INFO] [_internal.py -- _log:122] [ * Detected change in 'F:\\yjcloud-learn\\python_learn\\frame_api\\src\\app\\api\\v1\\learn.py', reloading]
[2020-03-24 20:30:47,417] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 20:30:48,815] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 20:30:48,819] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 20:30:48,850] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 130-757-431]
[2020-03-24 20:30:48,862] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-24 20:31:07,453] [INFO] [_internal.py -- _log:122] [ * Detected change in 'F:\\yjcloud-learn\\python_learn\\frame_api\\src\\app\\api\\v1\\learn.py', reloading]
[2020-03-24 20:31:07,515] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 20:31:08,936] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 20:31:08,939] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 20:31:08,965] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 130-757-431]
[2020-03-24 20:31:08,976] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-24 20:33:31,461] [INFO] [_internal.py -- _log:122] [ * Detected change in 'F:\\yjcloud-learn\\python_learn\\frame_api\\src\\app\\api\\v1\\learn.py', reloading]
[2020-03-24 20:33:31,540] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 20:33:32,962] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 20:33:32,965] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 20:33:32,990] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 130-757-431]
[2020-03-24 20:33:33,000] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-24 20:36:09,558] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [24/Mar/2020 20:36:09] "POST /v1/learn/op_reason_trend HTTP/1.1" 500 -]
[2020-03-24 20:36:25,308] [INFO] [_internal.py -- _log:122] [ * Detected change in 'F:\\yjcloud-learn\\python_learn\\frame_api\\src\\app\\api\\v1\\learn.py', reloading]
[2020-03-24 20:36:25,393] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 20:36:26,749] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 20:36:26,752] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 20:36:26,778] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 130-757-431]
[2020-03-24 20:36:26,789] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-24 20:36:27,156] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [24/Mar/2020 20:36:27] "POST /v1/learn/op_reason_trend HTTP/1.1" 200 -]
[2020-03-24 20:46:50,368] [INFO] [_internal.py -- _log:122] [ * Detected change in 'F:\\yjcloud-learn\\python_learn\\frame_api\\src\\app\\api\\v1\\learn.py', reloading]
[2020-03-24 20:46:50,429] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 20:46:52,099] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 20:46:52,120] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 20:46:52,145] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 130-757-431]
[2020-03-24 20:46:52,155] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-24 20:56:31,991] [INFO] [_internal.py -- _log:122] [ * Detected change in 'F:\\yjcloud-learn\\python_learn\\frame_api\\src\\app\\api\\v1\\learn.py', reloading]
[2020-03-24 20:56:32,063] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 20:56:33,457] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 20:56:33,460] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 20:56:33,487] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 130-757-431]
[2020-03-24 20:56:33,498] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-24 20:56:34,137] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [24/Mar/2020 20:56:34] "POST /v1/learn/op_reason_trend HTTP/1.1" 200 -]
[2020-03-24 20:57:22,305] [INFO] [_internal.py -- _log:122] [ * Detected change in 'F:\\yjcloud-learn\\python_learn\\frame_api\\src\\app\\api\\v1\\learn.py', reloading]
[2020-03-24 20:57:22,375] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 20:57:23,739] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 20:57:23,742] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 20:57:23,766] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 130-757-431]
[2020-03-24 20:57:23,777] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-24 20:57:59,728] [INFO] [_internal.py -- _log:122] [ * Detected change in 'F:\\yjcloud-learn\\python_learn\\frame_api\\src\\app\\api\\v1\\learn.py', reloading]
[2020-03-24 20:57:59,787] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 20:58:01,129] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 20:58:01,132] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 20:58:01,157] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 130-757-431]
[2020-03-24 20:58:01,168] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-24 20:58:01,336] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [24/Mar/2020 20:58:01] "POST /v1/learn/op_reason_trend HTTP/1.1" 200 -]
[2020-03-24 21:00:27,008] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [24/Mar/2020 21:00:27] "POST /v1/learn/op_reason_trend HTTP/1.1" 200 -]
[2020-03-24 21:00:27,206] [INFO] [_internal.py -- _log:122] [ * Detected change in 'F:\\yjcloud-learn\\python_learn\\frame_api\\src\\app\\api\\v1\\learn.py', reloading]
[2020-03-24 21:00:27,265] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-24 21:00:28,598] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-24 21:00:28,601] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-24 21:00:28,626] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 130-757-431]
[2020-03-24 21:00:28,637] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-26 21:12:44,496] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-26 21:12:44,529] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-26 21:12:45,819] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-26 21:12:45,821] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-26 21:12:45,846] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 130-757-431]
[2020-03-26 21:12:45,856] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-26 21:13:26,631] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [26/Mar/2020 21:13:26] "POST /v1/know/op-dura-business-list HTTP/1.1" 200 -]
[2020-03-26 21:15:26,790] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [26/Mar/2020 21:15:26] "POST /v1/know/op-dura-business-list HTTP/1.1" 200 -]
[2020-03-26 21:21:04,686] [INFO] [_internal.py -- _log:122] [ * Detected change in 'F:\\yjcloud-learn\\python_learn\\frame_api\\src\\app\\api\\v1\\know.py', reloading]
[2020-03-26 21:21:04,766] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-26 21:21:06,108] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-26 21:21:06,110] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-26 21:21:06,135] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 130-757-431]
[2020-03-26 21:21:06,146] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-26 21:21:06,664] [INFO] [_internal.py -- _log:122] [127.0.0.1 - - [26/Mar/2020 21:21:06] "POST /v1/know/op-dura-business-list HTTP/1.1" 200 -]
[2020-03-26 21:26:23,782] [INFO] [_internal.py -- _log:122] [ * Detected change in 'F:\\yjcloud-learn\\python_learn\\frame_api\\src\\app\\api\\v1\\know.py', reloading]
[2020-03-26 21:26:23,868] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-26 21:26:25,337] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-26 21:26:25,340] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-26 21:26:25,365] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 130-757-431]
[2020-03-26 21:26:25,377] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
[2020-03-26 21:27:27,792] [INFO] [_internal.py -- _log:122] [ * Detected change in 'F:\\yjcloud-learn\\python_learn\\frame_api\\src\\app\\api\\v1\\know.py', reloading]
[2020-03-26 21:27:27,849] [INFO] [_internal.py -- _log:122] [ * Restarting with stat]
[2020-03-26 21:27:29,173] [INFO] [server.py -- __init__:149] [Server initialized for threading.]
[2020-03-26 21:27:29,175] [WARNING] [_internal.py -- _log:122] [ * Debugger is active!]
[2020-03-26 21:27:29,200] [INFO] [_internal.py -- _log:122] [ * Debugger PIN: 130-757-431]
[2020-03-26 21:27:29,210] [INFO] [_internal.py -- _log:122] [ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
